
CREATE TABLE CURRENCY_ID (
	CURRENCY_ID VARCHAR(3) NOT NULL,
	PRIMARY KEY (CURRENCY_ID)
);

CREATE TABLE CURRENCY (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	EXPIRED DATETIME NOT NULL,
	CURRENCY_ID VARCHAR(3) NOT NULL,
	CREATED DATETIME NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL,
	INITIALS VARCHAR(3),
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, EXPIRED, CURRENCY_ID)
);

CREATE TABLE FREQUENCY_ID (
	FREQUENCY_ID VARCHAR(3) NOT NULL,
	PRIMARY KEY (FREQUENCY_ID)
);

CREATE TABLE FREQUENCY (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	FREQUENCY_ID VARCHAR(3) NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL,
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, FREQUENCY_ID)
);

CREATE TABLE FUNDS_DESTINATION_ID (
	FUNDS_DESTINATION_ID VARCHAR(3) NOT NULL,
	PRIMARY KEY (FUNDS_DESTINATION_ID)
);

CREATE TABLE FUNDS_DESTINATION (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	FUNDS_DESTINATION_ID VARCHAR(3) NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL,
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, FUNDS_DESTINATION_ID)
);

CREATE TABLE GEOGRAPHIC_ZONE_ID (
	GEOGRAPHIC_ZONE_ID VARCHAR(6) NOT NULL,
	PRIMARY KEY (GEOGRAPHIC_ZONE_ID)
);

CREATE TABLE GEOGRAPHIC_ZONE (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	GEOGRAPHIC_ZONE_ID VARCHAR(6) NOT NULL,
	DESCRIPTION VARCHAR(100),
	COORDINATE_TYPE VARCHAR(20) NOT NULL,
	P11 VARCHAR(50) NOT NULL,
	P12 VARCHAR(50) NOT NULL,
	P21 VARCHAR(50),
	P22 VARCHAR(50),
	P31 VARCHAR(50),
	P32 VARCHAR(50),
	P41 VARCHAR(50),
	P42 VARCHAR(50),
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, GEOGRAPHIC_ZONE_ID)
);

CREATE TABLE PARTNER_ID (
	PARTNER_ID VARCHAR(10) NOT NULL,
	USER_ID VARCHAR(20) NOT NULL,
	PRIMARY KEY (PARTNER_ID, USER_ID)
);

CREATE TABLE PARTNER (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	EXPIRED DATETIME NOT NULL,
	PARTNER_ID VARCHAR(10) NOT NULL,
	USER_ID VARCHAR(20) NOT NULL,
	CREATED DATETIME NOT NULL,
	PERSON_ID INTEGER NOT NULL,
	ACTIVITY VARCHAR(300),
	FREQUENCY_ID VARCHAR(3),
	MEETING_DAY INTEGER,
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, EXPIRED, PARTNER_ID, USER_ID)
);

CREATE TABLE PARTNER_GROUP_ID (
	PARTNER_GROUP_ID VARCHAR(15) NOT NULL,
	PRIMARY KEY (PARTNER_GROUP_ID)
);

CREATE TABLE PARTNER_GROUP (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	EXPIRED DATETIME NOT NULL,
	PARTNER_GROUP_ID VARCHAR(15) NOT NULL,
	CREATED DATETIME NOT NULL,
	GROUP_DESCRIPTION VARCHAR(100) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	ACTIVITY VARCHAR(300),
	USER_ID VARCHAR(20) NOT NULL,
	FREQUENCY_ID VARCHAR(3) NOT NULL,
	MEETING_DAY INTEGER,
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, EXPIRED, PARTNER_GROUP_ID)
);

CREATE TABLE PARTNER_GROUP_MEMBER_ID (
	PARTNER_GROUP_MEMBER_ID VARCHAR(15) NOT NULL,
	PRIMARY KEY (PARTNER_GROUP_MEMBER_ID)
);

CREATE TABLE PARTNER_GROUP_MEMBER (
	COMPANY_ID VARCHAR(4) NOT NULL,
	EXPIRED DATETIME NOT NULL,
	PARTNER_GROUP_MEMBER_ID VARCHAR(15) NOT NULL,
	CREATED DATETIME NOT NULL,
	PARTNER_GROUP_ID VARCHAR(15) NOT NULL,
	PERSON_ID INTEGER NOT NULL,
	RESPONSABILITY_ID VARCHAR(3) NOT NULL,
	OBSERVATIONS VARCHAR(200),
	VERSION INTEGER NOT NULL DEFAULT '0',
	PRIMARY KEY (COMPANY_ID, EXPIRED, PARTNER_GROUP_MEMBER_ID)
);

CREATE TABLE PRODUCT_ASESSOR_ID (
	USER_ID VARCHAR(20) NOT NULL,
	PRODUCT_ID VARCHAR(3) NOT NULL,
	PRIMARY KEY (USER_ID, PRODUCT_ID)
);

CREATE TABLE PRODUCT_ASESSOR (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	USER_ID VARCHAR(20) NOT NULL,
	PRODUCT_ID VARCHAR(3) NOT NULL,
	OBSERVATIONS VARCHAR(50),
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, USER_ID, PRODUCT_ID)
);

CREATE TABLE PRODUCT_MICROCREDIT_ID (
	PRODUCT_ID VARCHAR(3) NOT NULL,
	PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE PRODUCT_MICROCREDIT (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	EXPIRED DATETIME NOT NULL,
	PRODUCT_ID VARCHAR(3) NOT NULL,
	CREATED DATETIME NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL,
	CURRENCY_ID VARCHAR(3) NOT NULL,
	MIN_AMOUNT DECIMAL(19,6) NOT NULL,
	MAX_AMOUNT DECIMAL(19,6) NOT NULL,
	MIN_PERIOD BIGINT NOT NULL,
	MAX_PERIOD BIGINT NOT NULL,
	RATE DECIMAL(19,6) NOT NULL,
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, EXPIRED, PRODUCT_ID)
);

CREATE TABLE QUOTA_TYPE_ID (
	QUOTA_TYPE_ID VARCHAR(3) NOT NULL,
	PRIMARY KEY (QUOTA_TYPE_ID)
);

CREATE TABLE QUOTA_TYPE (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	QUOTA_TYPE_ID VARCHAR(3) NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL,
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, QUOTA_TYPE_ID)
);

CREATE TABLE RECOMMENDATION_ID (
	SOLICITUDE_ID VARCHAR(25) NOT NULL,
	PRIMARY KEY (SOLICITUDE_ID)
);

CREATE TABLE RECOMMENDATION (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	EXPIRED DATETIME NOT NULL,
	SOLICITUDE_ID VARCHAR(25) NOT NULL,
	CREATED DATETIME NOT NULL,
	DOCUMENTS VARCHAR(500) NOT NULL,
	ECONOMIC_UNIT VARCHAR(500) NOT NULL,
	FAMILY_UNIT VARCHAR(500) NOT NULL,
	PAYMENT_MORALE VARCHAR(500) NOT NULL,
	CREDIT_HISTORY VARCHAR(500) NOT NULL,
	PROPOSAL VARCHAR(25) NOT NULL,
	VERSION INTEGER NOT NULL DEFAULT '0',
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, EXPIRED, SOLICITUDE_ID)
);

CREATE TABLE RESPONSABILITY_ID (
	RESPONSABILITY_ID VARCHAR(3) NOT NULL,
	PRIMARY KEY (RESPONSABILITY_ID)
);

CREATE TABLE RESPONSABILITY (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	EXPIRED DATETIME NOT NULL,
	RESPONSABILITY_ID VARCHAR(3) NOT NULL,
	CREATED DATETIME NOT NULL,
	NAME VARCHAR(40) NOT NULL,
	DESCRIPTION VARCHAR(60),
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, EXPIRED, RESPONSABILITY_ID)
);

CREATE TABLE SOLICITUDE_ID (
	SOLICITUDE_ID VARCHAR(25) NOT NULL,
	PRIMARY KEY (SOLICITUDE_ID)
);

CREATE TABLE SOLICITUDE (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	EXPIRED DATETIME NOT NULL,
	SOLICITUDE_ID VARCHAR(25) NOT NULL,
	CREATED DATETIME NOT NULL,
	ACCOUNT VARCHAR(25),
	ASSESSOR VARCHAR(20) NOT NULL,
	PARTNER_CLIENT_ID VARCHAR(10),
	GROUP_CLIENT_ID VARCHAR(10),
	SOLICITUDE_DATE DATETIME NOT NULL,
	APPROVAL_DATE DATETIME,
	DISBURSEMENT_DATE DATETIME,
	EXPIRATION_DATE DATETIME NOT NULL,
	PRODUCT_ID VARCHAR(3) NOT NULL,
	STATUS_ID VARCHAR(3) NOT NULL,
	NUMBER_RENEWAL INTEGER NOT NULL,
	AMOUNT DECIMAL(19,6) NOT NULL,
	TERM BIGINT NOT NULL,
	QUOTA_TYPE_ID VARCHAR(3) NOT NULL,
	NUMBER_QUOTAS INTEGER NOT NULL,
	PAYMENT_FREQUENCY_ID VARCHAR(3) NOT NULL,
	FUNDS_DESTINATION_ID VARCHAR(3) NOT NULL,
	DESTINATION_DESCRIPTION VARCHAR(3) NOT NULL,
	VERSION INTEGER NOT NULL DEFAULT '0',
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, EXPIRED, SOLICITUDE_ID)
);

CREATE TABLE SOLICITUDE_STATUS_ID (
	STATUS_ID VARCHAR(3) NOT NULL,
	PRIMARY KEY (STATUS_ID)
);

CREATE TABLE SOLICITUDE_STATUS (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	STATUS_ID VARCHAR(3) NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL,
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, STATUS_ID)
);

CREATE TABLE ZONE_ASESSOR_ID (
	USER_ID VARCHAR(20) NOT NULL,
	GEOGRAPHIC_ZONE_ID VARCHAR(6) NOT NULL,
	PRIMARY KEY (USER_ID, GEOGRAPHIC_ZONE_ID)
);

CREATE TABLE ZONE_ASESSOR (
	COMPANY_ID VARCHAR(4) NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	USER_ID VARCHAR(20) NOT NULL,
	GEOGRAPHIC_ZONE_ID VARCHAR(6) NOT NULL,
	OBSERVATIONS VARCHAR(50),
	PRIMARY KEY (COMPANY_ID, LANGUAGE_ID, USER_ID, GEOGRAPHIC_ZONE_ID)
);

ALTER TABLE CURRENCY ADD CONSTRAINT CURRENCY_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE CURRENCY ADD CONSTRAINT CURRENCY_ID_FK FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY_ID (CURRENCY_ID);
ALTER TABLE CURRENCY ADD CONSTRAINT CURRENCY_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE FREQUENCY ADD CONSTRAINT FREQUENCY_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE FREQUENCY ADD CONSTRAINT FREQUENCY_ID_FK FOREIGN KEY (FREQUENCY_ID) REFERENCES FREQUENCY_ID (FREQUENCY_ID);
ALTER TABLE FREQUENCY ADD CONSTRAINT FREQUENCY_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE FUNDS_DESTINATION ADD CONSTRAINT FUNDS_DESTINATION_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE FUNDS_DESTINATION ADD CONSTRAINT FUNDS_DESTINATION_ID_FK FOREIGN KEY (FUNDS_DESTINATION_ID) REFERENCES FUNDS_DESTINATION_ID (FUNDS_DESTINATION_ID);
ALTER TABLE FUNDS_DESTINATION ADD CONSTRAINT FUNDS_DESTINATION_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE GEOGRAPHIC_ZONE ADD CONSTRAINT GEOGRAPHIC_ZONE_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE GEOGRAPHIC_ZONE ADD CONSTRAINT GEOGRAPHIC_ZONE_ID_FK FOREIGN KEY (GEOGRAPHIC_ZONE_ID) REFERENCES GEOGRAPHIC_ZONE_ID (GEOGRAPHIC_ZONE_ID);
ALTER TABLE GEOGRAPHIC_ZONE ADD CONSTRAINT GEOGRAPHIC_ZONE_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE PARTNER ADD CONSTRAINT PARTNER_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE PARTNER ADD CONSTRAINT PARTNER_FREQ_ID_FK FOREIGN KEY (FREQUENCY_ID) REFERENCES FREQUENCY_ID (FREQUENCY_ID);
ALTER TABLE PARTNER ADD CONSTRAINT PARTNER_ID_FK FOREIGN KEY (PARTNER_ID, USER_ID) REFERENCES PARTNER_ID (PARTNER_ID, USER_ID);
ALTER TABLE PARTNER ADD CONSTRAINT PARTNER_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE PARTNER ADD CONSTRAINT PARTNER_PERSON_ID_FK FOREIGN KEY (PERSON_ID) REFERENCES PERSON_ID (PERSON_ID);
ALTER TABLE PARTNER ADD CONSTRAINT PARTNER_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT_ID (USER_ID);
ALTER TABLE PARTNER_GROUP ADD CONSTRAINT PARTNER_GROUP_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE PARTNER_GROUP ADD CONSTRAINT PARTNER_GROUP_FREQ_ID_FK FOREIGN KEY (FREQUENCY_ID) REFERENCES FREQUENCY_ID (FREQUENCY_ID);
ALTER TABLE PARTNER_GROUP ADD CONSTRAINT PARTNER_GROUP_ID_FK FOREIGN KEY (PARTNER_GROUP_ID) REFERENCES PARTNER_GROUP_ID (PARTNER_GROUP_ID);
ALTER TABLE PARTNER_GROUP ADD CONSTRAINT PARTNER_GROUP_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE PARTNER_GROUP ADD CONSTRAINT PARTNER_GROUP_PAR_GRP_ID_FK FOREIGN KEY (PARTNER_GROUP_ID) REFERENCES PARTNER_GROUP_ID (PARTNER_GROUP_ID);
ALTER TABLE PARTNER_GROUP ADD CONSTRAINT PARTNER_GROUP_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT_ID (USER_ID);
ALTER TABLE PARTNER_GROUP_MEMBER ADD CONSTRAINT PARTNER_GROUP_MEMBER_ID_FK FOREIGN KEY (PARTNER_GROUP_MEMBER_ID) REFERENCES PARTNER_GROUP_MEMBER_ID (PARTNER_GROUP_MEMBER_ID);
ALTER TABLE PARTNER_GROUP_MEMBER ADD CONSTRAINT PARTNER_GRP_MEM_GRP_ID_FK FOREIGN KEY (PARTNER_GROUP_ID) REFERENCES PARTNER_GROUP_ID (PARTNER_GROUP_ID);
ALTER TABLE PARTNER_GROUP_MEMBER ADD CONSTRAINT PARTNER_GRP_MEM_PERSON_ID_FK FOREIGN KEY (PERSON_ID) REFERENCES PERSON_ID (PERSON_ID);
ALTER TABLE PARTNER_GROUP_MEMBER ADD CONSTRAINT PARTNER_GRP_MEM_RESP_ID_FK FOREIGN KEY (RESPONSABILITY_ID) REFERENCES RESPONSABILITY_ID (RESPONSABILITY_ID);
ALTER TABLE PARTNER_GROUP_MEMBER ADD CONSTRAINT PARTN_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE PRODUCT_ASESSOR ADD CONSTRAINT PRODUCT_ASESSOR_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE PRODUCT_ASESSOR ADD CONSTRAINT PRODUCT_ASESSOR_ID_FK FOREIGN KEY (USER_ID, PRODUCT_ID) REFERENCES PRODUCT_ASESSOR_ID (USER_ID, PRODUCT_ID);
ALTER TABLE PRODUCT_ASESSOR ADD CONSTRAINT PRODUCT_ASESSOR_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE PRODUCT_ASESSOR ADD CONSTRAINT PROD_ASSESSOR_PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_MICROCREDIT_ID (PRODUCT_ID);
ALTER TABLE PRODUCT_ASESSOR ADD CONSTRAINT PROD_ASSESSOR_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT_ID (USER_ID);
ALTER TABLE PRODUCT_MICROCREDIT ADD CONSTRAINT PRODUCT_MICROCREDIT_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE PRODUCT_MICROCREDIT ADD CONSTRAINT PRODUCT_MICROCREDIT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_MICROCREDIT_ID (PRODUCT_ID);
ALTER TABLE PRODUCT_MICROCREDIT ADD CONSTRAINT PRODUCT_MIC_CURRENCY_ID_FK FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY_ID (CURRENCY_ID);
ALTER TABLE PRODUCT_MICROCREDIT ADD CONSTRAINT PRODU_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE QUOTA_TYPE ADD CONSTRAINT QUOTA_TYPE_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE QUOTA_TYPE ADD CONSTRAINT QUOTA_TYPE_ID_FK FOREIGN KEY (QUOTA_TYPE_ID) REFERENCES QUOTA_TYPE_ID (QUOTA_TYPE_ID);
ALTER TABLE QUOTA_TYPE ADD CONSTRAINT QUOTA_TYPE_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE RECOMMENDATION ADD CONSTRAINT RECOMMENDATION_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE RECOMMENDATION ADD CONSTRAINT RECOMMENDATION_ID_FK FOREIGN KEY (SOLICITUDE_ID) REFERENCES RECOMMENDATION_ID (SOLICITUDE_ID);
ALTER TABLE RECOMMENDATION ADD CONSTRAINT RECOMMENDATION_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE RECOMMENDATION ADD CONSTRAINT RECOMMENDATION_SOLICITUDE_ID FOREIGN KEY (SOLICITUDE_ID) REFERENCES SOLICITUDE_ID (SOLICITUDE_ID);
ALTER TABLE RESPONSABILITY ADD CONSTRAINT RESPONSABILITY_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE RESPONSABILITY ADD CONSTRAINT RESPONSABILITY_ID_FK FOREIGN KEY (RESPONSABILITY_ID) REFERENCES RESPONSABILITY_ID (RESPONSABILITY_ID);
ALTER TABLE RESPONSABILITY ADD CONSTRAINT RESPONSABILITY_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE SOLICITUDE ADD CONSTRAINT SOLICITUDE_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE SOLICITUDE ADD CONSTRAINT SOLICITUDE_FUNDS_DEST_ID_FK FOREIGN KEY (FUNDS_DESTINATION_ID) REFERENCES FUNDS_DESTINATION_ID (FUNDS_DESTINATION_ID);
ALTER TABLE SOLICITUDE ADD CONSTRAINT SOLICITUDE_GROUP_CLIENT_ID_FK FOREIGN KEY (GROUP_CLIENT_ID) REFERENCES PARTNER_GROUP_ID (PARTNER_GROUP_ID);
ALTER TABLE SOLICITUDE ADD CONSTRAINT SOLICITUDE_ID_FK FOREIGN KEY (SOLICITUDE_ID) REFERENCES SOLICITUDE_ID (SOLICITUDE_ID);
ALTER TABLE SOLICITUDE ADD CONSTRAINT SOLICITUDE_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE SOLICITUDE ADD CONSTRAINT SOLICITUDE_PARTNER_CLIE_ID_FK FOREIGN KEY (PARTNER_CLIENT_ID) REFERENCES PARTNER_ID (PARTNER_ID);
ALTER TABLE SOLICITUDE ADD CONSTRAINT SOLICITUDE_PAY_FREQ_ID_FK FOREIGN KEY (PAYMENT_FREQUENCY_ID) REFERENCES FREQUENCY_ID (FREQUENCY_ID);
ALTER TABLE SOLICITUDE ADD CONSTRAINT SOLICITUDE_PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_MICROCREDIT_ID (PRODUCT_ID);
ALTER TABLE SOLICITUDE ADD CONSTRAINT SOLICITUDE_QUOTA_TYPE_ID_FK FOREIGN KEY (QUOTA_TYPE_ID) REFERENCES QUOTA_TYPE_ID (QUOTA_TYPE_ID);
ALTER TABLE SOLICITUDE ADD CONSTRAINT SOLICITUDE_SOL_STATUS_ID_FK FOREIGN KEY (STATUS_ID) REFERENCES SOLICITUDE_STATUS_ID (STATUS_ID);
ALTER TABLE SOLICITUDE ADD CONSTRAINT SOLICITUDE_USER_ACCOUNT_ID_FK FOREIGN KEY (ASSESSOR) REFERENCES USER_ACCOUNT_ID (USER_ID);
ALTER TABLE SOLICITUDE_STATUS ADD CONSTRAINT SOLICITUDE_STATUS_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE SOLICITUDE_STATUS ADD CONSTRAINT SOLICITUDE_STATUS_ID_FK FOREIGN KEY (STATUS_ID) REFERENCES SOLICITUDE_STATUS_ID (STATUS_ID);
ALTER TABLE SOLICITUDE_STATUS ADD CONSTRAINT SOLICITUDE_STATUS_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE ZONE_ASESSOR ADD CONSTRAINT ZONE_ASESSOR_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE ZONE_ASESSOR ADD CONSTRAINT ZONE_ASESSOR_ID_FK FOREIGN KEY (USER_ID, GEOGRAPHIC_ZONE_ID) REFERENCES ZONE_ASESSOR_ID (USER_ID, GEOGRAPHIC_ZONE_ID);
ALTER TABLE ZONE_ASESSOR ADD CONSTRAINT ZONE_ASESSOR_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID);
ALTER TABLE ZONE_ASESSOR ADD CONSTRAINT ZONE_ASE_GEO_ZONE_ID_FK FOREIGN KEY (GEOGRAPHIC_ZONE_ID) REFERENCES GEOGRAPHIC_ZONE_ID (GEOGRAPHIC_ZONE_ID);
ALTER TABLE ZONE_ASESSOR ADD CONSTRAINT ZONE_ASE_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT_ID (USER_ID);
