package mobile.tools.common.enums;

public enum ObjectionCode {

	SUCCESS("OK", "PROCESO EXITOSO"),
	FAILED("ERROR", "PROCESO FALLIDO"),
	FAILED_("ERROR_", "{0}"),
	NO_MESSAGE("NO_MENSAJE", "NINGUN MENSAJE RECIBIDO"),
	NO_CLASS("NO_CLASE", "CLASE {0} NO ENCONTRADA"),
	NO_SESSION("NO_SESION", "EL USUARIO {0} NO TIENE UNA SESION DEFINIDA"),
	NO_PROFILE("NO_PERFIL", "EL USUARIO {0} NO TIENE UN PERFIL DEFINIDO"),
	ROLE_PROCESS("NO_PERMISO", "EL PROCESO {0} NO ESTA DEFINIDO PARA EL ROL {1}"),
	HOST_ADDRESS("HOST_IP", "EL HOST {0} NO ESTA DEFINIDO"),
	USER_NOT("NO_USUARIO", "EL USUARIO {0} NO EXISTE"),
	USER_NOT_ACTIVE("USUARIO_INACTIVO", "EL USUARIO {0} NO ESTA ACTIVO"),
	USER_PASSWORD("CONTRASEÑA_INCORRECTA", "LA CONTRASEÑA INGRESADA ES INCORRECTA"),
	USER_SESSION("USUARIO_SESION", "EL USUARIO {0} TIENE UNA SESIÓN ACTIVA EN EL TERMINAL {1}"),
	USER_STATUS("USUARIO_ESTATUS", "EL ESTATUS PARA EL USUARIO {0} ES {1}"),
	NULL_VALUES("VALORES_NULOS", "ENVÍO DE VALORES NULOS"),
	DB_ERROR("BD_ERROR", "ERROR DE BASE DE DATOS"),
	DB_CONNECTION_ERROR("BD_CONEXION_ERROR", "ERROR AL CONECTARSE CON LA BASE DE DATOS"),
	DB_DUPLICATE_PK("BD_CODIGO_DUPLICADO", "CÓDIGO DE REGISTRO DUPLICADO"),
	DB_FOREIGN_KEY("BD_REFERENCIA", "ERROR DE REFERENCIA"),
	DB_NULL("BD_NULOS", "NO SE HA ENVIADO ALGUNOS VALORES"),
	DB_QUERY_ERROR("BD_CONSULTA_ERROR", "ERROR AL EJECUTAR LA CONSULTA"),
	SIMULATOR_CONNECTION_ERROR("CONEXION_SIMULADOR", "ERROR AL CONECTARSER CON EL SIMULADOR");
	
	String code;
	String message;

	ObjectionCode(String code, String message) {
		this.code = code;
		this.message = message;
	}

	public String getCode() {
		return code;
	}
	
	public String getMessage() {
		return message;
	}
}